export const SELECT_RESERVATION_DATE = 'SELECT_RESERVATION_DATE';
export const SELECT_NR_OF_PERSONS = 'SELECT_NR_OF_PERSONS';
export const SELECT_RESERVATION_HOUR = 'SELECT_RESERVATION_HOUR';

export const MAKE_RESERVATION_START = 'MAKE_RESERVATION_START';
export const MAKE_RESERVATION_SUCCESS = 'MAKE_RESERVATION_SUCCESS';
export const MAKE_RESERVATION_ERROR = 'MAKE_RESERVATION_ERROR';

