export const FETCH_PENDING_RESERVATIONS_START = 'FETCH_PENDING_RESERVATIONS_START';
export const FETCH_PENDING_RESERVATIONS_SUCCESS = 'FETCH_PENDING_RESERVATIONS_SUCCESS';
export const FETCH_PENDING_RESERVATIONS_ERROR = 'FETCH_PENDING_RESERVATIONS_ERROR';

export const APPROVE_RESERVATION_START = 'APPROVE_RESERVATION_START';
export const APPROVE_RESERVATION_SUCCESS = 'APPROVE_RESERVATION_SUCCESS';
export const APPROVE_RESERVATION_ERROR = 'APPROVE_RESERVATION_ERROR';

export const REJECT_RESERVATION_START = 'REJECT_RESERVATION_START';
export const REJECT_RESERVATION_SUCCESS = 'REJECT_RESERVATION_SUCCESS';
export const REJECT_RESERVATION_ERROR = 'REJECT_RESERVATION_ERROR';
