export const FETCH_ALL_PLACES_START = 'FETCH_ALL_PLACES';
export const FETCH_ALL_PLACES_SUCCESS = 'FETCH_ALL_PLACES_SUCCESS';
export const FETCH_ALL_PLACES_ERROR = 'FETCH_ALL_PLACES_ERROR';

export const SELECT_FILTER = 'SELECT_FILTER';
export const ADD_FILTERED_DATA = 'ADD_FILTERED_DATA';
